export default [
  { _text: "Alabama" },
  { _text: "Alaska" },
  { _text: "Arizona" },
  { _text: "Arkansas" },
  { _text: "California" },
  { _text: "Colorado" },
  { _text: "Connecticut" },
  { _text: "Delaware" },
  { _text: "Florida" },
  { _text: "Georgia" },
  { _text: "Hawaii" },
  { _text: "Idaho" },
  { _text: "Illinois" },
  { _text: "Indiana" },
  { _text: "Iowa" },
  { _text: "Kansas" },
  { _text: "Kentucky" },
  { _text: "Louisiana" },
  { _text: "Maine" },
  { _text: "Maryland" },
  { _text: "Massachusetts" },
  { _text: "Michigan" },
  { _text: "Minnesota" },
  { _text: "Mississippi" },
  { _text: "Missouri" },
  { _text: "Montana" },
  { _text: "Nebraska" },
  { _text: "Nevada" },
  { _text: "New Hampshire" },
  { _text: "New Jersey" },
  { _text: "New Mexico" },
  { _text: "New York" },
  { _text: "North Carolina" },
  { _text: "North Dakota" },
  { _text: "Ohio" },
  { _text: "Oklahoma" },
  { _text: "Oregon" },
  { _text: "Pennsylvania" },
  { _text: "Rhode Island" },
  { _text: "South Carolina" },
  { _text: "South Dakota" },
  { _text: "Tennessee" },
  { _text: "Texas" },
  { _text: "Utah" },
  { _text: "Vermont" },
  { _text: "Virginia" },
  { _text: "Washington" },
  { _text: "West Virginia" },
  { _text: "Wisconsin" },
  { _text: "Wyoming" },
];
