export default [
  {
    name: "Clarke",
    email: "cwinwright0@blogtalkradio.com",
    car: "Porsche",
    order: 20,
  },
  {
    name: "Torrey",
    email: "torteaux1@dedecms.com",
    car: "Dodge",
    order: 43,
  },
  {
    name: "Chad",
    email: "cwestmacott2@goo.ne.jp",
    car: "Ford",
    order: 36,
  },
  {
    name: "Gloriane",
    email: "gpersicke3@latimes.com",
    car: "Lincoln",
    order: 52,
  },
  {
    name: "Alfred",
    email: "amcrae4@mediafire.com",
    car: "Lexus",
    order: 75,
  },
  {
    name: "Lindi",
    email: "lkliemchen5@rakuten.co.jp",
    car: "Chrysler",
    order: 34,
  },
  {
    name: "Reg",
    email: "rsmardon6@hc360.com",
    car: "Dodge",
    order: 78,
  },
  {
    name: "Yalonda",
    email: "ygudgen7@e-recht24.de",
    car: "Isuzu",
    order: 24,
  },
  {
    name: "Shep",
    email: "sgreasley8@tamu.edu",
    car: "Land Rover",
    order: 79,
  },
  {
    name: "Rori",
    email: "rcapewell9@netlog.com",
    car: "Suzuki",
    order: 27,
  },
  {
    name: "Mechelle",
    email: "mlancastlea@auda.org.au",
    car: "Acura",
    order: 33,
  },
  {
    name: "Nana",
    email: "ndemeyerb@php.net",
    car: "Ford",
    order: 73,
  },
  {
    name: "Padget",
    email: "pfurzerc@xrea.com",
    car: "BMW",
    order: 62,
  },
  {
    name: "Sigfried",
    email: "sbuckhamd@sitemeter.com",
    car: "Mitsubishi",
    order: 94,
  },
  {
    name: "Jocko",
    email: "jlowdee@yellowbook.com",
    car: "Mazda",
    order: 68,
  },
  {
    name: "Dolorita",
    email: "dsignoretf@qq.com",
    car: "Chevrolet",
    order: 55,
  },
  {
    name: "Linnea",
    email: "lcailg@columbia.edu",
    car: "Porsche",
    order: 74,
  },
  {
    name: "Kimble",
    email: "kdegouyh@bloglovin.com",
    car: "Volvo",
    order: 28,
  },
  {
    name: "Roby",
    email: "rmaggsi@phoca.cz",
    car: "Mercury",
    order: 2,
  },
  {
    name: "Fredrika",
    email: "fleimsterj@redcross.org",
    car: "Audi",
    order: 62,
  },
];
