# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Generate Demos

on: workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup npm
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - run: npm ci
      - name: Build project
        run: npm run build

      - name: Build demos
        run: npm run demo:build

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_TOKEN }}

      - name: Check Azure Identity
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az account show --query "{name:name, user:user.name, type:user.type, subscriptionId:id}" -o table
      - name: Check Azure CLI version
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az --version

      - name: Delete old demos
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob delete-batch --source '$web' --pattern "demos/*" --account-name prsv --auth-mode login

      - name: Upload to Azure blob storage
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob upload-batch -d '$web/demos' -s ./demo-dist --account-name prsv --auth-mode login

      - name: Set Subscription Context
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Purge CDN
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az afd endpoint purge --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --profile-name ${{ secrets.AZURE_CDN_PROFILE_NAME }} --endpoint-name ${{ secrets.AZURE_CDN_ENDPOINT }} --content-paths '/*'  --no-wait

      - name: Azure logout
        run: |
          az logout
