name: Release Docs

on: workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GA: ${{ secrets.GA }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup npm
        uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - run: npm ci
      - name: Build project
        run: npm run build

      - name: Build docs
        run: npm run docs:build
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_TOKEN }}

      - name: Delete old docs
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage remove -c '$web' --exclude-path "demos" --recursive --account-name prsv

      - name: Upload to Azure blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name prsv -d '$web' -s ./docs/.vuepress/dist

      - name: Azure logout
        run: |
          az logout
