name: Release Docs

on: workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GA: ${{ secrets.GA }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup npm
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - run: npm ci
      - name: Build project
        run: npm run build

      - name: Build docs
        run: npm run docs:build

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_TOKEN }}

      # az storage remove -c '$web' --exclude-path "demos" --recursive --account-name prsv
      # azure cli "remove" deprecated; Must list all blobs to exclude demos/ and delete them one by one
      # 1. List all blobs using query filter to exclude 'demos/'
      # 2. Pipes the filtered list to delete command
      # 3. Maintains the demos folder content
      # 4. Uses proper authentication
      # 5. Uses `xargs` to iterate over the list and delete each blob
      - name: Delete old blobs (docs) except those in demos folder
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob list --container-name '$web' --account-name prsv --auth-mode login --query "[?!starts_with(name, 'demos/')].[name]" -o tsv |
            xargs -I {} az storage blob delete --container-name '$web' --name {} --account-name prsv --auth-mode login

      - name: Upload docs to Azure blob storage
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob upload-batch -d '$web' -s ./docs/.vuepress/dist --account-name prsv --auth-mode login

      - name: Set Subscription Context
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Purge CDN
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az afd endpoint purge --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --profile-name ${{ secrets.AZURE_CDN_PROFILE_NAME }} --endpoint-name ${{ secrets.AZURE_CDN_ENDPOINT }} --content-paths '/*'  --no-wait

      - name: Azure logout
        run: |
          az logout
